The first metric is crime. In this case, we are trying to build a measurement of the security degree of the community.                  
The measurement can be divided into two parts: the probability of encounter crime and how severe the crime is.                      
For the first part, we need to figure out the frequency of each type of crime and proportion of criminal in the whole population of the community.                
For the second part, we need to have a rank of the severe degree of differernt types of crime, and figure a weight to quantify the potential harm of these crimes. The weight will be represented by numbers between 0 and 100, where 100 means death.                     
And the final measurement will be built like this:         
            
1.Find out the proportion of criminal in the poplulation of community, namely the probability of encountering a criminal in the community.( a%)      
2.Use the frequency of different types of crime to predict what would be the next action of this criminal. (m% for murder, n% for robber and so on ) we assume that the type of crime won't convert to each other and even the slightest crime is intolerable.           
3.Times the fequency by the weight and add them together.(100m% for murder+70n% for robber...) The result will be taken as a criminal's personal
dangerous degree.        
4.Times the criminal dangerous degree by the probability of encountering a criminal, the result will be the community dangerous degree.                   
                
The lower the community dangerous degree, the better the security degree of the community is.

In [122]:
import pandas as pd
import numpy as np
import geopandas as gpd
crime = pd.read_csv("crime.csv")
list1=pd.DataFrame(crime.iloc[0:,[0,2,6,7]])
list1.head(20)

,Neighborhood,Population (2010),Part 1 Crime per 100 Persons (2010),Part 2 Crime per 100 Persons (2010)
0,Allegheny Center,933,7.6,15.1
1,Allegheny West,462,8.2,10.6
2,Allentown,"2,500",6.4,10.1
3,Arlington,"1,869",2.7,4.5
4,Arlington Heights,244,7.8,15.2
5,Banksville,"4,144",1.5,2.0
6,Bedford Dwellings,"1,202",3.5,6.7
7,Beechview,"7,974",2.4,3.8
8,Beltzhoover,"1,925",4.3,6.8
9,Bloomfield,"8,442",5.4,4.4
10,Bluff,"6,600",1.6,2.9
11,Bon Air,808,3.2,6.8
12,Brighton Heights,"7,247",3.3,3.9
13,Brookline,"13,214",1.8,3.0
14,California-Kirkbride,761,8.4,11.7
15,Carrick,"10,113",4.5,5.3
16,Central Business District,"3,629",21.7,15.6
17,Central Lawrenceville,"4,482",3.9,5.2
18,Central Northside,"2,923",4.0,8.4
19,Central Oakland,"6,086",3.9,2.7

In [132]:
a=list1.iloc[0:,2]
b=list1.iloc[0:,3]
c=float(list1.iloc[0,1].replace(',',''))

#this list shows the probability of encountering a criminal in the community.
# PEC=probability of encountering a criminal
list2={'neighborhood':crime.iloc[0:,0],'PEC':(a+b)/c}

x=pd.DataFrame(list2)
x1=x.sort_values(by="PEC").head()
x1

           neighborhood       PEC
31            Fairywood  0.000965
54        New Homestead  0.001179
75  Squirrel Hill North  0.002465
58              Oakwood  0.003001
45        Lincoln Place  0.003215

Above are five communities that you are least likely to encounter a criminal.

In [143]:
a1=crime.iloc[0:,8]
a2=crime.iloc[0,9]
a3=crime.iloc[0,10]
a4=crime.iloc[0,11]
a5=crime.iloc[0,12]
a6=crime.iloc[0,13]
a7=crime.iloc[0,14]
k=a1+a2+a3+a4+a5+a6+a7
#PDD=personal dangerous degree
PDD=100*a1/k+95*a2/k+90*a3/k+90*a4/k+95*a5/k+90*a6/k+90*a7/k
list3={'neighborhood':crime.iloc[0:,0],'PDD':PDD}
y=pd.DataFrame(list3)
y1=y.sort_values(by="PDD").head()
y1

        neighborhood        PDD
0   Allegheny Center  90.833333
77         St. Clair  90.833333
35        Glen Hazel  90.833333
36        Greenfield  90.833333
37              Hays  90.833333

Above are five communities that the criminals inside are "least" dangerous.

In [145]:
#CDD=community dangerous degree
CDD=PDD*PEC
list_final={'neighborhood':crime.iloc[0:,0],'CDD':CDD}
z=pd.DataFrame(list_final)
z1=z.sort_values(by="CDD").head()
z1

        neighborhood         CDD
0   Allegheny Center  220.998571
77         St. Clair  220.998571
35        Glen Hazel  220.998571
36        Greenfield  220.998571
37              Hays  220.998571

above are five most safety community in Pittsburgh.